//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chipotle.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStock
    {
        public ItemStock()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ItemId { get; set; }
        public int RestaurantNo { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public int StockOnHand { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
