//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chipotle.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPrice
    {
        public int OrderNo { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Tax { get; set; }
        public Nullable<decimal> Others { get; set; }
        public decimal Total { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
