//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chipotle.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderNo { get; set; }
        public int ItemId { get; set; }
        public int Qunatity { get; set; }
        public string ItemNotes { get; set; }
    
        public virtual ItemStock ItemStock { get; set; }
        public virtual Order Order { get; set; }
    }
}
