//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chipotle.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderNo { get; set; }
        public string OrderTitle { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public int OrderMode { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public string EventName { get; set; }
        public string EventNotes { get; set; }
        public int OrderedBy { get; set; }
        public int RestaurantNo { get; set; }
        public int PaymentMode { get; set; }
        public Nullable<int> ShippedBy { get; set; }
        public string ShipMode { get; set; }
        public string PickupBy { get; set; }
        public int CreatedBy { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual OrderMode OrderModes { get; set; }
        public virtual OrderPrice OrderPrice { get; set; }
        public virtual PaymentMode PaymentModes { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual OrderStatus OrderStatuses { get; set; }
        public virtual User User { get; set; }
    }
}
