//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chipotle.Entity.Models
{
    using Repository;
    using System;
    using System.Collections.Generic;
    
    public partial class User : EntityBase
    {
        public User()
        {
            //this.LoginAudits = new HashSet<LoginAudit>();
            //this.Orders = new HashSet<Order>();
        }
    
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsActive { get; set; }
        public bool IsLoggedIn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        //public virtual ICollection<LoginAudit> LoginAudits { get; set; }
        //public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
    }
}
